name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file src/main/docker/Dockerfile.native.multistage --tag docker.pkg.github.com/lars1974/images/quarkus-first:$(date +%s)
    - name: Build the Docker image
      run: docker push docker.pkg.github.com/lars1974/images/quarkus-first:$(date +%s)
